# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ['index.Rmd']

name: render-rmarkdown

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@v1
      
      - uses: r-lib/actions/setup-pandoc@v1
      
      - uses: r-lib/actions/setup-renv@v2
      
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown", "prettydoc"))'
      
      - name: render index.Rmd
        run: Rscript -e 'rmarkdown::render("index.Rmd")'

      - name: Commit index.html
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add index.html
          git commit -m "Re-build index.html" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
